name: drinkly
description: A new Flutter project.
version: 2.0.0+4
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog: ^0.10.0+5
  auto_route: ^1.0.2
  awesome_dialog: ^2.0.0-nullsafety.0
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.1
  equatable: ^2.0.0
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.1
  flip_card: 
    git:
      url: https://github.com/BrunoJurkovic/flip_card.git
  flutter_bloc: ^7.0.0
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  intl: ^0.17.0
  introduction_screen: ^2.0.0
  shared_preferences: ^2.0.5
  tcard: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.2
  bloc_test: ^8.0.0
  build_runner: ^1.11.5
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true
